## 系统默认端口
server:
  port: 8080
  undertow:
    ## 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    ## 不要设置过大，如果过大，启动项目会报错：打开文件数过多
    io-threads: 8
    ## 阻塞任务线程池, 当执行类似servlet请求阻塞IO操作, undertow会从这个线程池中取得线程
    ## 它的值设置取决于系统线程执行任务的阻塞系数，默认值是IO线程数*8
    worker-threads: 64
    ## 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    ## 每块buffer的空间大小,越小的空间被利用越充分，不要设置太大，以免影响其他应用，合适即可
    buffer-size: 1024
    ## 是否分配的直接内存(NIO直接分配的堆外内存)
    direct-buffers: true
  ## 不带项目名访问
  servlet:
    context-path: /


spring:
  datasource:
    ## 数据库配置
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.107.224.194:3306/osen-dev?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: Pangyi@19971125
    hikari:
      ## 最小空闲连接数量
      minimum-idle: 5
      ## 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      ## 连接池最大连接数，默认是10
      maximum-pool-size: 15
      ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      ## 连接池母子
      pool-name: DatebookHikariCP
      ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 180000
      ## 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  ## 彩色打印
  output:
    ansi:
      enabled: always
  ## redis配置
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 15
        max-idle: 5
        max-wait: -1


## 日志配置
logging:
  path: /logging
  config: classpath:log/logback-spring.xml
  level:
    com.osen.cloud.model: debug


## mybatis配置
mybatis-plus:
  type-aliases-package: com.osen.cloud.**.entity
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


## 统一请求地址头
restful:
  prefix: /api/lampblack