## 系统默认端口
server:
  undertow:
    ## 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    ## 不要设置过大，如果过大，启动项目会报错：打开文件数过多
    io-threads: 8
    ## 阻塞任务线程池, 当执行类似servlet请求阻塞IO操作, undertow会从这个线程池中取得线程
    ## 它的值设置取决于系统线程执行任务的阻塞系数，默认值是IO线程数*8
    worker-threads: 64
    ## 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    ## 每块buffer的空间大小,越小的空间被利用越充分，不要设置太大，以免影响其他应用，合适即可
    buffer-size: 1024
    ## 是否分配的直接内存(NIO直接分配的堆外内存)
    direct-buffers: true
  ## 不带项目名访问
  servlet:
    context-path: /


# 系统多环境配置
spring:
  profiles:
    active: dev


## 日志配置
logging:
  path: /system_logging
  config: classpath:log/logback-spring.xml
  level:
    com.osen.cloud.model: debug


## mybatis配置
mybatis-plus:
  type-aliases-package: com.osen.cloud.**.entity
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


## 统一请求地址头
restful:
  prefix: /api/cloud